services:
  - type: web
    name: omega-vx
    env: python
    plan: starter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python omega_vx_bot.py
    envVars:
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: APCA_API_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: ALPACA_PAPER
        value: "true"
      - key: ALPACA_DATA_FEED
        value: iex
      - key: ALLOW_PLAIN_BUY_FALLBACK
        value: "1"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
